/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.NumeroComplejo;
import javax.swing.JOptionPane;

/**
 *
 * @author SP
 */
public class Ejercicio3 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio3
     */
    public Ejercicio3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRealUno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRealDos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtImaginarioUno = new javax.swing.JTextField();
        txtImaginarioDos = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtResultadoReal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtResultadoImaginario = new javax.swing.JTextField();
        cmdCalcular = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        cmbOperacionesBasicas = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calisto MT", 2, 18)); // NOI18N
        jLabel1.setText("Ejercicio3");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, -1, 20));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel2.setText("Numero Real");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        txtRealUno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRealUnoKeyTyped(evt);
            }
        });
        jPanel1.add(txtRealUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 70, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel3.setText("Numero Real");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        txtRealDos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRealDosKeyTyped(evt);
            }
        });
        jPanel1.add(txtRealDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 70, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel4.setText("Numero Imaginario");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel5.setText("Numero Imaginario");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        txtImaginarioUno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtImaginarioUnoKeyTyped(evt);
            }
        });
        jPanel1.add(txtImaginarioUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 70, -1));

        txtImaginarioDos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtImaginarioDosKeyTyped(evt);
            }
        });
        jPanel1.add(txtImaginarioDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 70, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        jLabel6.setText("Resultados");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, -1));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        jLabel7.setText("Numero Real");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        txtResultadoReal.setEditable(false);
        txtResultadoReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultadoRealActionPerformed(evt);
            }
        });
        jPanel2.add(txtResultadoReal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 110, -1));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        jLabel8.setText("Numero Imaginario");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        txtResultadoImaginario.setEditable(false);
        txtResultadoImaginario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultadoImaginarioActionPerformed(evt);
            }
        });
        jPanel2.add(txtResultadoImaginario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 90, -1));

        cmdCalcular.setBackground(new java.awt.Color(255, 255, 255));
        cmdCalcular.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        cmdCalcular.setForeground(new java.awt.Color(0, 51, 204));
        cmdCalcular.setText("Calcular");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });
        jPanel2.add(cmdCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        cmdBorrar.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        cmdBorrar.setForeground(new java.awt.Color(255, 51, 153));
        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 240, 150));

        cmbOperacionesBasicas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sumar", "Restar", "Multiplicar", "Dividir  " }));
        jPanel1.add(cmbOperacionesBasicas, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(679, 220));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtResultadoRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultadoRealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultadoRealActionPerformed

    private void txtResultadoImaginarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultadoImaginarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultadoImaginarioActionPerformed

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed
       int operacion,numreal1,numreal2,numimaginario1,numimaginario2;NumeroComplejo f=null,f1,f2; 
       if(txtRealUno.getText().trim().isEmpty()){ 
           JOptionPane.showMessageDialog(this,"Se requiere llenar los campos obligatorios","Error",JOptionPane.ERROR_MESSAGE);
           txtRealUno.requestFocusInWindow();
       }else if(txtRealDos.getText().trim().isEmpty()){ 
           JOptionPane.showMessageDialog(this,"Se requiere llenar los campos obligatorios","Error",JOptionPane.ERROR_MESSAGE);
           txtRealDos.requestFocusInWindow();
       }else if(txtImaginarioUno.getText().trim().isEmpty()){ 
           JOptionPane.showMessageDialog(this,"Se requiere llenar los campos obligatorios","Error",JOptionPane.ERROR_MESSAGE);
           txtImaginarioUno.requestFocusInWindow();
       }else if(txtImaginarioDos.getText().trim().isEmpty()){ 
           JOptionPane.showMessageDialog(this,"Se requiere llenar los campos obligatorios","Error",JOptionPane.ERROR_MESSAGE);
           txtImaginarioDos.requestFocusInWindow();
       }else{ 
           JOptionPane.showMessageDialog(this,"Campos obligatorios agregados satisfactoriamente"); 
           operacion=cmbOperacionesBasicas.getSelectedIndex(); 
           numreal1=Integer.parseInt(txtRealUno.getText());
           numreal2=Integer.parseInt(txtRealDos.getText());
           numimaginario1=Integer.parseInt(txtImaginarioUno.getText()); 
           numimaginario2=Integer.parseInt(txtImaginarioDos.getText()); 
           f1=new NumeroComplejo(numreal1,numimaginario1); 
           f2=new NumeroComplejo(numreal2,numimaginario2); 
           switch(operacion){ 
               case 0: 
                f=f1.Suma(f2);
               break; 
               case 1: 
                f=f1.resta(f2); 
               break; 
               case 2: 
                f=f1.multiplicacion(f2); 
               break; 
               case 3: 
                f=f1.division(f2); 
               break;
           } 
           txtResultadoReal.setText(""+f.getNumeroreal()); 
           txtResultadoImaginario.setText(""+f.getNumeroimaginario());
       }        
       
    }//GEN-LAST:event_cmdCalcularActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
        txtImaginarioUno.setText("");
        txtImaginarioDos.setText("");
        txtResultadoImaginario.setText("");
        txtRealUno.setText("");
        txtRealDos.setText("");
        txtResultadoReal.setText("");
        txtResultadoReal.requestFocusInWindow();
        cmbOperacionesBasicas.setSelectedIndex(0);
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void txtRealUnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRealUnoKeyTyped
       char c=evt.getKeyChar(); 
       if(!Character.isDigit(c)){ 
        getToolkit(); 
        evt.consume();
       
       }
    }//GEN-LAST:event_txtRealUnoKeyTyped

    private void txtRealDosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRealDosKeyTyped
       char c=evt.getKeyChar(); 
       if(!Character.isDigit(c)){ 
        getToolkit(); 
        evt.consume();
       }
    }//GEN-LAST:event_txtRealDosKeyTyped

    private void txtImaginarioUnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImaginarioUnoKeyTyped
        char c=evt.getKeyChar(); 
       if(!Character.isDigit(c)){ 
        getToolkit(); 
        evt.consume(); 
       }
    }//GEN-LAST:event_txtImaginarioUnoKeyTyped

    private void txtImaginarioDosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImaginarioDosKeyTyped
        char c=evt.getKeyChar(); 
       if(!Character.isDigit(c)){ 
        getToolkit(); 
        evt.consume(); 
       }
    }//GEN-LAST:event_txtImaginarioDosKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbOperacionesBasicas;
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtImaginarioDos;
    private javax.swing.JTextField txtImaginarioUno;
    private javax.swing.JTextField txtRealDos;
    private javax.swing.JTextField txtRealUno;
    private javax.swing.JTextField txtResultadoImaginario;
    private javax.swing.JTextField txtResultadoReal;
    // End of variables declaration//GEN-END:variables
}





